name: test

on:
  workflow_dispatch:
    inputs:
      silent:
        type: boolean
        required: false
        description: "Skip Logging"

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{steps.branch.outputs.branch}}
    steps:
      - id: branch
        shell: bash
        run: echo $PATH

  after-message:
    if: github.event.inputs.silent == 'false'
    runs-on: ubuntu-latest
    needs: [ check-branch ]
    steps:
      - run: echo ${{github.event.inputs.silent}}